spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3311/spa?autoReconnect=true
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mariadb://localhost:3311/spa?autoReconnect=true
    username: root
    password: 1234
    # change upload file size
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        50MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.naver.com
    port: 465
    username: sasinttt@naver.com
    password: Ntjdfyddl1!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com 
          starttls:
            enable: true
  messages:
    basename: classpath:message/security_message.properties
    encoding: utf-8
    
logging:
  config: classpath:log/logback.xml
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
  defaultCount: true # The default parameter of the paging plug-in is in the form of default-count. The parameter of the customized extension must be case - consistent
  
mybatis:
  mapper-locations: mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  
api:
  openapi:
    url: http://openapi.seoul.go.kr:8088/
    key: 54596478416e657631303078566f6567
#log4jdbc:
#  drivers: org.mariadb.jdbc.Driver
#log4jdbc.drivers:org.mariadb.jdbc.Driver