spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3311/spa?autoReconnect=true
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mariadb://localhost:3311/spa?autoReconnect=true
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.naver.com
    port: 587
    username: sasinttt@naver.com
    password: Ntjdfyddl1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
logging:
  config: classpath:log/logback.xml
  
mybatis:
  mapper-locations: mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  
#log4jdbc:
#  drivers: org.mariadb.jdbc.Driver
#log4jdbc.drivers:org.mariadb.jdbc.Driver    
  